name: Cypress Tests
run-name: ${{ github.actor }} is running Cypress tests
on: [push]
jobs:
  basic-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Cypress tests
        run: npx cypress run
